services:
  blabin:
    build:
      context: .
      dockerfile: blabin.Dockerfile
    container_name: controller
    env_file:
      - .env
    environment:
      - TZ=${TZ:-Etc/UTC}
      - MLFLOW_URI_LOCAL=http://127.0.0.1:8081
    command: ["/app/scripts/blabin-entrypoint.sh"]
    network_mode: "service:mlflow-proxy"
    restart: unless-stopped
    # platform: linux/arm64/v8

  mlflow-proxy:
    build:
      context: .
      dockerfile: mlflow.Dockerfile
    container_name: mlflow-proxy
    env_file:
      - .env
    environment:
      - SERVICE=mlflow
      - PORT=8081
      - BIND_ADDRESS=0.0.0.0
    ports:
      - "8081:8081"
    restart: unless-stopped
